tags:
  - name: "Product Management"
    description: "Endpoints related to managing products, vendors, and categories."

paths:
  /product/vendor:
    get:
      tags:
        - "Product Management"
      summary: "Get all vendors"
      description: "This endpoint fetches a list of all vendors."
      responses:
        200:
          description: "List of vendors retrieved successfully"
        500:
          description: "Error fetching vendors"

  /product/category:
    get:
      tags:
        - "Product Management"
      summary: "Get all categories"
      description: "This endpoint fetches a list of all categories."
      responses:
        200:
          description: "List of categories retrieved successfully"
        500:
          description: "Error fetching categories"
  
  /product/addNew:
    post:
      tags:
        - "Product Management"
      summary: "Add a new product"
      description: "This endpoint allows adding a new product to the inventory."
      parameters:
        - name: "product_name"
          in: "body"
          description: "Name of the product"
          required: true
          type: "string"
        - name: "status"
          in: "body"
          description: "Status of the product"
          required: true
          type: "string"
        - name: "category_name"
          in: "body"
          description: "Category name of the product"
          required: true
          type: "string"
        - name: "vendors"
          in: "body"
          description: "Vendors associated with the product"
          required: true
          type: "array"
          items:
            type: "string"
        - name: "quantity_in_stock"
          in: "body"
          description: "Quantity of the product available in stock"
          required: true
          type: "integer"
        - name: "unit_price"
          in: "body"
          description: "Price of the product per unit"
          required: true
          type: "number"
        - name: "product_image"
          in: "body"
          description: "Image URL of the product"
          required: true
          type: "string"
        - name: "full_image"
          in: "body"
          description: "Full image URL of the product"
          required: true
          type: "string"
        - name: "branchId"
          in: "body"
          description: "Branch ID where the product is available"
          required: true
          type: "integer"
      responses:
        201:
          description: "Product added successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
              productId:
                type: "integer"
        400:
          description: "Product already exists"
        500:
          description: "Error adding product"

  /product/del/{id}:
    put:
      tags:
        - "Product Management"
      summary: "Delete a product (soft delete)"
      description: "This endpoint marks a product as deleted (soft delete)."
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the product to be deleted"
          required: true
          type: "string"
      responses:
        200:
          description: "Product status updated to 99 (soft delete)"
        500:
          description: "Error updating product status"

  /product/update:
    put:
      tags:
        - "Product Management"
      summary: "Update an existing product"
      description: "This endpoint allows updating an existing product's details."
      parameters:
        - name: "product_id"
          in: "body"
          description: "ID of the product to be updated"
          required: true
          type: "integer"
        - name: "product_name"
          in: "body"
          description: "Updated name of the product"
          required: true
          type: "string"
        - name: "status"
          in: "body"
          description: "Updated status of the product"
          required: true
          type: "string"
        - name: "category_id"
          in: "body"
          description: "Updated category ID for the product"
          required: true
          type: "integer"
        - name: "vendors"
          in: "body"
          description: "Updated vendors for the product"
          required: true
          type: "array"
          items:
            type: "string"
        - name: "quantity_in_stock"
          in: "body"
          description: "Updated quantity in stock"
          required: true
          type: "integer"
        - name: "unit_price"
          in: "body"
          description: "Updated unit price of the product"
          required: true
          type: "number"
      responses:
        200:
          description: "Product updated successfully"
        500:
          description: "Error updating product"
